packaging_format = 2

id = "strapi"
name = "Strapi"
description.en = "Strapi.EN"
description.fr = "Strapi.FR"

version = "0.1"

maintainers = []

[upstream]
license = "MIT"
code = "https://github.com/dooxe/strapi_ynh"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
[install.domain]
type = "domain"

[install.path]
type = "path"
default = "/"

#[install.with_sftp]
#ask.en = "Do you need a SFTP access?"
#ask.fr = "Avez-vous besoin d'un accès SFTP ?"
#type = "boolean"
#default = true

#[install.password]
#type = "password"
#optional = true

[install.init_main_permission]
type = "group"
default = "admins"

#[install.phpversion]
#ask.en = "Choose a PHP version you want to use for your app"
#ask.fr = "Choisissez une version PHP que vous souhaitez utiliser pour votre application"
#type = "select"
#choices = ["none", "7.4", "8.0", "8.1", "8.2"]
#default = "8.0"

#[install.database]
#ask.en = "Do you need a database?"
#ask.fr = "Avez-vous besoin d'une base de données ?"
#type = "select"
#choices = ["none", "mysql", "postgresql"]
#default = "none"


[resources]
[resources.system_user]

[resources.install_dir]

[resources.permissions]
main.url = "/"

[resources.apt]
