#!/bin/bash
#--------------------------------------------------------------------------
source _common.sh
source /usr/share/yunohost/helpers
#--------------------------------------------------------------------------
ynh_script_progression --message="Installing NodeJS" --weight=2
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

ynh_script_progression --message="Adding NGINX config..." --weight=2
ynh_add_nginx_config

#domain=`ynh_app_setting_get --app=$app --key=install.domain`

ynh_script_progression --message="Cloning strapi..." --weight=2
npx --yes create-strapi-app "$install_dir/strapi" --no-run --quickstart

ls "$install_dir"

ynh_script_progression --message="Starting strapi..." --weight=2
pwd=`pwd`
cd "$install_dir/strapi"
ynh_script_progression --message="Running strapi in background..." --weight=2
npm run develop & 
cd $pwd

ynh_script_progression --message="Installation of $app completed" --last
