#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Installing NodeJS" --weight=2
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

ynh_script_progression --message="Cloning strapi..." --weight=2
npx --yes create-strapi-app "$install_dir/strapi" --no-run --quickstart

ynh_script_progression --message="Starting strapi..." --weight=2
pwd=`pwd`
cd "$install_dir/strapi"

url=`ynh_app_setting_get --app=$app --key=install.domain`

toto=`ls`
echo $ls

cat << "EOF" > config/server.js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: "${url}",
  app: {
    keys: env.array('APP_KEYS'),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  },
});
EOF

ynh_script_progression --message="Adding NGINX config..." --weight=2
ynh_add_nginx_config

ynh_script_progression --message="Running strapi in background..." --weight=2
npm run develop & 
cd $pwd

ynh_script_progression --message="Installation of $app completed" --last