#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Installing NodeJS" --weight=2
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

ynh_script_progression --message="Cloning strapi..." --weight=2
npx create-strapi-app "$install_dir/strapi" --quickstart

ynh_script_progression --message="Installation of $app completed" --last